### ISSUE TITLE
May I translate your blog into Simplified Chinese?

### ISSUE THREAD

**Issue by ringora** [popovicu/risc-v-bare-metal-fake-bios#2]
Hello, recently I read your "Bare metal programming with RISC-V guide" blog post on your website and have learned a lot from it. Since I couldn't find any other way to reach out to you directly, I am creating this issue to express my gratitude. I am planning to translate this blog post into Simplified Chinese and publish it on my personal blog. May I kindly ask for your permission to do so?

**Comment by popovicu** [comment]
Hey, sorry for the late reply. Yes, please go ahead! I'd appreciate a link back to the original article if you don't mind. Otherwise, please go for it!

**Comment by ringora** [comment]
No problem, I've completed the translation of the article today and have published it on my blog. I've included a citation of your article link within the translated text. Here's the link to the translated version: https://www.cnblogs.com/fenfeng9/p/18158918, and I've also created a repository containing the example program with Chinese annotations. Thank you very much for your generosity.

**Comment by popovicu** [comment]
Thanks a lot!
